export const ENV_VARS = {
SMTP_HOST: 'SMTP_HOST',
SMTP_PORT: 'SMTP_PORT',
SMTP_USER: 'SMTP_USER',
SMTP_PASS: 'SMTP_PASS',
SMTP_FROM: 'SMTP_FROM',

JWT_SECRET: 'JWT_SECRET',

FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
};


